export const shohidDB = [
  {
    imageUrl: 'https://shohid.info/shohid/abu-sayed.jpg',
    name: 'Abu Sayed',
    role: 'Student',
    institution: 'Begum Rokeya University, Rangpur',
    date: '16th July, 2024',
    rank: '1',
  },
  {
    imageUrl: 'https://shohid.info/shohid/faisal-ahmed-shanto.jpg',
    name: 'Faisal Ahmed Shanto',
    role: 'Student',
    institution: 'Omargani M.E.S. College, Chittagong',
    date: '16th July, 2024',
    rank: '2',
  },
  {
    imageUrl: 'https://shohid.info/shohid/md-wasim-akrum.jpg',
    name: 'Md. Wasim Akrum',
    role: 'Student',
    institution: 'Chittagong College, Chittagong',
    date: '16th July, 2024',
    rank: '3',
  },
  {
    imageUrl: 'https://shohid.info/shohid/tahmid-tamim.jpg',
    name: 'Tahmid Tamim',
    role: 'Student',
    institution: 'Qadir Mollah High School, Narsingdi',
    date: '18th July, 2024',
    rank: '4',
  },
  {
    imageUrl: 'https://shohid.info/shohid/shykh-aashhabul-yamin.jpg',
    name: 'Shykh Aashhabul Yamin',
    role: 'Student',
    institution: 'Military Institute of Science and Technology',
    date: '18th July, 2024',
    rank: '5',
  },
  {
    imageUrl: 'https://shohid.info/shohid/jahiduzzaman-tanvin.jpg',
    name: 'Jahiduzzaman Tanvin',
    role: 'Student',
    institution: 'Islamic University of Technology, Gazipur.',
    date: '18th July, 2024',
    rank: '6',
  },
  {
    imageUrl: 'https://shohid.info/shohid/farhan-faiyaaz.jpg',
    name: 'Farhan Faiyaaz',
    role: 'Student',
    institution: 'Dhaka Residential Model College, Mohammadpur',
    date: '18th July, 2024',
    rank: '7',
  },
  {
    imageUrl: 'https://shohid.info/shohid/irfan-bhuiyan.jpg',
    name: 'Irfan Bhuiyan',
    role: 'Student',
    institution: 'United International University',
    date: '19th July, 2024',
    rank: '8',
  },
  {
    imageUrl: 'https://shohid.info/shohid/mir-mugdho.jpg',
    name: 'Mir Mugdho',
    role: 'Student',
    institution: 'Bangladesh University of professionals',
    date: '18th July, 2024',
    rank: '9',
  },
  {
    imageUrl: 'https://shohid.info/shohid/shah-newaz-fahad.jpg',
    name: 'Shah Newaz Fahad',
    role: 'Student',
    institution: 'East West University',
    date: '18th July, 2024',
    rank: '10',
  },
  {
    imageUrl: 'https://shohid.info/shohid/shakil-parvej.jpg',
    name: 'Shakil Parvej',
    role: 'Student',
    institution: 'Manarat International University',
    date: '18th July, 2024',
    rank: '11',
  },
  {
    imageUrl: 'https://shohid.info/shohid/sheikh-fahmin-zafor.jpg',
    name: 'Sheikh Fahmin Zafor',
    role: 'Student',
    institution: 'Tongi Govt. College',
    date: '18th July, 2024',
    rank: '12',
  },
  {
    imageUrl: 'https://shohid.info/shohid/zillur-sheikh.jpg',
    name: 'Zillur Sheikh',
    role: 'Student',
    institution: 'Imperial College, Dhaka',
    date: '18th July, 2024',
    rank: '13',
  },
  {
    imageUrl: 'https://shohid.info/shohid/dipto-hw.jpg',
    name: 'Dipto Hw',
    role: 'Student',
    institution: 'Madaripur Government College',
    date: '18th July, 2024',
    rank: '14',
  },
  {
    imageUrl: 'https://shohid.info/shohid/rudro-sen.jpg',
    name: 'Rudro Sen',
    role: 'Student',
    institution: 'Shahjalal University of Science and Technology, Sylhet',
    date: '18th July, 2024',
    rank: '15',
  },
  {
    imageUrl: 'https://shohid.info/shohid/mehedi-hasan.jpg',
    name: 'Mehedi Hasan',
    role: 'Journalist',
    institution: 'Dhaka Times',
    date: '18th July, 2024',
    rank: '16',
  },
  {
    imageUrl: 'https://shohid.info/shohid/emon-ahmed.jpg',
    name: 'Emon Ahmed',
    role: '18 years old, Palash Thana, Narsingdi Sadar Upazila. - Source: BBC Bangla',
    institution: '',
    date: '18th July, 2024',
    rank: '17',
  },
  {
    imageUrl: 'https://shohid.info/shohid/siam-1.jpg',
    name: 'Siam',
    role: 'An employee at a battery shop in Gulistan. He was shot at Hanif Flyover during a clash while returning home at night. Source: Jugantor',
    institution: '',
    date: '18th July, 2024',
    rank: '18',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Dulal Matbor',
    role: 'Driver, He was driving through the area during the clash. - Source: BBC Bangla',
    institution: '',
    date: '18th July, 2024',
    rank: '19',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Muhammad',
    role: 'Location: Ajimpur, Detailed information is not yet known. Source: Prothom Alo',
    institution: '',
    date: '18th July, 2024',
    rank: '20',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Sharif Hasan',
    role: 'Student',
    institution: 'Imperial College, Dhaka',
    date: '18th July, 2024',
    rank: '21',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Imon Miah',
    role: 'Student',
    institution: 'Govt. Shahid Asad College, Shibpur, Narsingdi',
    date: '18th July, 2024',
    rank: '22',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Shakil Hasan',
    role: 'Journalist',
    institution: 'Daily Vorer Awaz',
    date: '18th July, 2024',
    rank: '23',
  },
  {
    imageUrl: 'https://shohid.info/shohid/kalid-hasan-saifullah.jpg',
    name: 'Khalid Hasan Saifullah',
    role: 'Student',
    institution: 'Imperial College, Dhaka',
    date: '18th July, 2024',
    rank: '24',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Sabbir Hosen',
    role: 'Employee',
    institution: 'Organ Limited Care',
    date: '18th July, 2024',
    rank: '25',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Mohammad Imad',
    role: 'Student',
    institution: 'Patiya Government College, Chittagong',
    date: '18th July, 2024',
    rank: '26',
  },
  {
    imageUrl: 'https://shohid.info/shohid/asif-iqbal.jpg',
    name: 'Asif Iqbal',
    role: 'Student',
    institution: 'Independent University Bangladesh, Dhaka',
    date: '18th July, 2024',
    rank: '27',
  },
  {
    imageUrl: 'https://shohid.info/shohid/hridoy-chandra-tarua.jpg',
    name: 'Hridoy Chandra Tarua ',
    role: 'Student',
    institution: 'University of Chittagong',
    date: '18th July, 2024',
    rank: '28',
  },
  {
    imageUrl: 'https://shohid.info/shohid/rahat-hossain.jpg',
    name: 'Rahat Hossain',
    role: 'Student',
    institution: 'Nawab Habibullah Model School & College, Dhaka',
    date: '18th July, 2024',
    rank: '29',
  },
  {
    imageUrl: 'https://shohid.info/shohid/sabbir-hossen-jhenaidah.jpg',
    name: 'Sabbir Hossen',
    role: 'Madrasha Student',
    institution: '',
    date: '18th July, 2024',
    rank: '30',
  },
  {
    imageUrl: 'https://shohid.info/shohid/dr-sajib-sarker.jpg',
    name: 'Dr. Sajib Sarker',
    role: 'Doctor',
    institution: 'Tairunnessa Memorial Medical College & Hospital, Tongi',
    date: '18th July, 2024',
    rank: '31',
  },
  {
    imageUrl: 'https://shohid.info/shohid/asif-hasan.jpg',
    name: 'Asif Hasan ',
    role: 'Student',
    institution: 'Northern University Bangladesh',
    date: '18th July, 2024',
    rank: '32',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Hasib Iqbal',
    role: 'Employee',
    institution: 'A private institution in Dhaka',
    date: '19th July, 2024',
    rank: '33',
  },
  {
    imageUrl: 'https://shohid.info/shohid/mostofa-zaman-shomudro.jpg',
    name: 'Mostofa Zaman Shomudro',
    role: 'Student',
    institution: 'Ideal School And College, Banasree, Dhaka',
    date: '19th July, 2024',
    rank: '34',
  },
  {
    imageUrl: 'https://shohid.info/shohid/abu-taher-md-turab.jpg',
    name: 'Abu Taher Md Turab',
    role: 'Journalist',
    institution: 'Daily Jalalabad',
    date: '19th July, 2024',
    rank: '35',
  },
  {
    imageUrl: 'https://shohid.info/shohid/nadim-mizan.jpg',
    name: 'Nadim Mizan',
    role: 'Teacher',
    institution: 'Coaching Centre',
    date: '19th July, 2024',
    rank: '36',
  },
  {
    imageUrl: 'https://shohid.info/shohid/abdul-goni.jpg',
    name: 'Abdul Goni',
    role: 'Location: Rampura-Badda, Detailed information is not yet known. Source: Prothom Alo',
    institution: '',
    date: '19th July, 2024',
    rank: '37',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Rakib',
    role: 'Location: Rampura-Badda, Detailed information is not yet known. Source: Prothom Alo',
    institution: '',
    date: '19th July, 2024',
    rank: '38',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Rasel',
    role: 'Location: Rampura-Badda, Detailed information is not yet known. Source: Prothom Alo',
    institution: '',
    date: '19th July, 2024',
    rank: '39',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Jubaer Bepari',
    role: 'businessman, was passing through the area of conflict as a pedestrian. Source: BBC Bangla',
    institution: '',
    date: '19th July, 2024',
    rank: '40',
  },
  {
    imageUrl: 'https://shohid.info/shohid/ridowan-sharif-riyad.jpg',
    name: 'Ridowan Sharif Riyad',
    role: 'Student',
    institution: 'Tongi Govt. College',
    date: '19th July, 2024',
    rank: '41',
  },
  {
    imageUrl: 'https://shohid.info/shohid/monirul-islam.jpg',
    name: 'Monirul Islam',
    role: 'Monirul Islam was tragically killed by a bullet shot in Mirpur ',
    institution: '',
    date: '19th July, 2024',
    rank: '42',
  },
  {
    imageUrl: 'https://shohid.info/shohid/ikram-hosen-kawsar.jpg',
    name: 'Ikram Hosen Kawsar',
    role: 'Student',
    institution: 'Kabi Nazrul Govt. College, Dhaka',
    date: '19th July, 2024',
    rank: '43',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Maruf Hosen',
    role: 'কুষ্টিয়া পলিটেকনিক ইনস্টিটিউট থেকে পড়াশোনা শেষ করে সপ্তাহ তিনেক আগে ঢাকায় এসেছিলেন চাকরি খুঁজতে। - সূত্র: বিবিসি বাংলা',
    institution: '',
    date: '19th July, 2024',
    rank: '44',
  },
  {
    imageUrl: 'https://shohid.info/shohid/maruf-hossain.jpg',
    name: 'Maruf Hossain',
    role: 'Student',
    institution: 'Akota Degree College, Barisal',
    date: '19th July, 2024',
    rank: '45',
  },
  {
    imageUrl: 'https://shohid.info/shohid/mahmudul-hasan-rizvi.jpg',
    name: 'Mahmudul Hasan Rizvi',
    role: 'Student',
    institution: 'Lakshmipur Polytechnic Institute',
    date: '19th July, 2024',
    rank: '46',
  },
  {
    imageUrl: 'https://shohid.info/shohid/mahamudul-rohman-soikot.jpg',
    name: 'Mahamudul Rohman Soikot',
    role: 'Student',
    institution: 'Govt. Mohammadpur Model School & College',
    date: '19th July, 2024',
    rank: '47',
  },
  {
    imageUrl: 'https://shohid.info/shohid/safkat-samir.jpg',
    name: 'Safkat Samir',
    role: 'Student',
    institution: 'Class Five, Madharsha',
    date: '19th July, 2024',
    rank: '48',
  },
  {
    imageUrl: 'https://shohid.info/shohid/mahabub-hasan-mamun.jpg',
    name: 'Mahabub Hasan Mamun',
    role: 'Employee',
    institution: 'bKash',
    date: '19th July, 2024',
    rank: '49',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Jashim Uddin',
    role: 'Day Laborer',
    institution: 'He worked as a day laborer in the Sipahibagh area of Dhaka',
    date: '19th July, 2024',
    rank: '50',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Merajul Islam Meraj',
    role: 'Employee',
    institution: 'Shaheed Jorrez Market, Rangpur',
    date: '19th July, 2024',
    rank: '51',
  },
  {
    imageUrl: 'https://shohid.info/shohid/ridone-sagar.jpg',
    name: 'Ridone Sagar',
    role: 'Student',
    institution: 'Mymensingh commerce college',
    date: '19th July, 2024',
    rank: '52',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Mahfuzur Rahmann Muhin',
    role: 'Student',
    institution: '',
    date: '19th July, 2024',
    rank: '53',
  },
  {
    imageUrl: 'https://shohid.info/shohid/arman-hossen-rustom.jpg',
    name: 'Arman Hossen Rustom',
    role: 'Student',
    institution: 'National Bangla High School',
    date: '19th July, 2024',
    rank: '54',
  },
  {
    imageUrl: 'https://shohid.info/shohid/md-jihad-hosen.jpg',
    name: 'Md. Jihad Hosen',
    role: 'Student',
    institution: 'Kabi Nazrul Govt. College',
    date: '19th July, 2024',
    rank: '55',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Muhammad Sami',
    role: 'Student',
    institution: 'Murari Chand College, Sylhet',
    date: '20th July, 2024',
    rank: '56',
  },
  {
    imageUrl: 'https://shohid.info/shohid/mosharraf-howlader.jpg',
    name: 'Mosharraf Howlader',
    role: 'Worker',
    institution: 'বোর্ড বাজার, গাজীপুর',
    date: '20th July, 2024',
    rank: '57',
  },
  {
    imageUrl: 'https://shohid.info/shohid/tahir-zaman-priyo.jpg',
    name: 'Tahir Zaman Priyo',
    role: 'Photo Journalist',
    institution: 'Streets of Dhaka',
    date: '20th July, 2024',
    rank: '58',
  },
  {
    imageUrl: 'https://shohid.info/shohid/rakib-hasan.jpg',
    name: 'Rakib Hasan',
    role: 'Student',
    institution: 'Military Institute of Science and Technology',
    date: '20th July, 2024',
    rank: '59',
  },
  {
    imageUrl: 'https://shohid.info/shohid/mukttakin-billah.jpg',
    name: 'Md. Mukttakin billah',
    role: 'Lab Technologist',
    institution: 'Enova diagnostic centre ',
    date: '20th July, 2024',
    rank: '60',
  },
  {
    imageUrl: 'https://shohid.info/shohid/amdadul-hossain.jpg',
    name: 'Amdadul Hossain',
    role: 'Driver',
    institution: '',
    date: '20th July, 2024',
    rank: '61',
  },
  {
    imageUrl: 'https://shohid.info/shohid/al-amin.jpg',
    name: 'Al Amin',
    role: 'Assistant',
    institution: 'Assistant, Tanjin Tisha (actress)',
    date: '21th July, 2024',
    rank: '62',
  },
  {
    imageUrl: 'https://shohid.info/shohid/omor-faruk.jpg',
    name: 'Omor Faruk',
    role: 'Student',
    institution: 'Kabi Nazrul Govt. College, Dhaka',
    date: '21th July, 2024',
    rank: '63',
  },
  {
    imageUrl: 'https://shohid.info/shohid/mahadi-pantho.jpg',
    name: 'Mahadi Hasan Pantho',
    role: 'Student',
    institution: 'Govt. Tolaram College, Narayanganj',
    date: '23th July, 2024',
    rank: '64',
  },
  {
    imageUrl: 'https://shohid.info/shohid/riya-gope.jpg',
    name: 'Riya Gope',
    role: 'Child',
    institution: '',
    date: '24th July, 2024',
    rank: '65',
  },
  {
    imageUrl: 'https://shohid.info/shohid/sheikh-shahriar-suharto.jpg',
    name: 'Sheikh Shahriar Shuharto',
    role: 'Student',
    institution: 'Ishwarganj Ideal College, Ishwarganj, Mymensingh.',
    date: '20th July, 2024',
    rank: '66',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Obaidullah',
    role: 'Student',
    institution: 'Northern University ',
    date: '19th July, 2024',
    rank: '67',
  },
  {
    imageUrl: 'https://shohid.info/shohid/safwan-rohan.jpg',
    name: 'Safwan Rohan',
    role: 'Student',
    institution: 'Dania College',
    date: '19th July, 2024',
    rank: '68',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Manik Mia',
    role: 'Auto Driver',
    institution: '',
    date: '18th July, 2024',
    rank: '69',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Mohammad Mahin',
    role: 'Shop Worker',
    institution: 'A shop in Dhaka',
    date: '21th July, 2024',
    rank: '70',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Shameem',
    role: 'Electrician',
    institution: 'Mohammadpur, Dhaka',
    date: '20th July, 2024',
    rank: '71',
  },
  {
    imageUrl: 'https://shohid.info/shohid/md-sagor-ahommed.jpg',
    name: 'MD. Sagor Ahommed',
    role: 'Student',
    institution: 'Government Bangla College, Mirpur',
    date: '19th July, 2024',
    rank: '72',
  },
  {
    imageUrl: 'https://shohid.info/shohid/md-masudur-rahman.jpg',
    name: 'MD. Masudur Rahman',
    role: 'Teacher',
    institution: 'Madrasa Ar Rahmania',
    date: '19th July, 2024',
    rank: '73',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Korban Ali',
    role: 'Businessman',
    institution: 'Savar Kacha Bazar',
    date: '20th July, 2024',
    rank: '74',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Tamim',
    role: 'Student',
    institution: '',
    date: '20th July, 2024',
    rank: '75',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Ubaydul Haque',
    role: 'Employee',
    institution: 'Dhaka',
    date: '19th July, 2024',
    rank: '76',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Farid',
    role: 'Employee',
    institution: 'Uttara Bank',
    date: '19th July, 2024',
    rank: '77',
  },
  {
    imageUrl: 'https://shohid.info/shohid/kamrul-hasan-rabbi.jpg',
    name: 'Kamrul Hasan Rabbi',
    role: 'Employee',
    institution: 'Walton Plaza',
    date: '21th July, 2024',
    rank: '78',
  },
  {
    imageUrl: 'https://shohid.info/shohid/riyaz-hosen.jpg',
    name: 'Riyaz Hosen',
    role: 'Student',
    institution: 'Ispahani College, Ramerkanda.',
    date: '19th July, 2024',
    rank: '79',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Toufiq',
    role: 'Student',
    institution: 'A shop in Shonir Akhra.',
    date: '21th July, 2024',
    rank: '80',
  },
  {
    imageUrl: 'https://shohid.info/shohid/md-ahsadun.jpg',
    name: 'MD. Ahasadun',
    role: 'Student',
    institution: 'UCEP Haji Sikandar Ali Technical School.',
    date: '18th July, 2024',
    rank: '81',
  },
  {
    imageUrl: 'https://shohid.info/shohid/ajijul.jpg',
    name: 'Ajijul',
    role: 'Student',
    institution: '',
    date: '21th July, 2024',
    rank: '82',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Said',
    role: 'Driver',
    institution: 'Mirpur 13',
    date: '19th July, 2024',
    rank: '83',
  },
  {
    imageUrl: 'https://shohid.info/shohid/md-mamun-miah.jpg',
    name: 'MD Mamun Miah',
    role: 'Student',
    institution: 'Govt. Titumir College',
    date: '19th July, 2024',
    rank: '84',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Md. Shakline',
    role: 'Student',
    institution: 'United International University',
    date: '18th July, 2024',
    rank: '85',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Emran Khalifa ',
    role: 'Employee',
    institution: 'Suvastu Nazar Valley Shopping Mall, Dhaka',
    date: '19th July, 2024',
    rank: '86',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Yousuf Ali Shawon',
    role: 'Employee',
    institution: 'A shop in Shonir Akhra.',
    date: '21th July, 2024',
    rank: '87',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'MD. Al-amin Hosen',
    role: 'Employee',
    institution: 'A tea-stall in Mohakhali.',
    date: '19th July, 2024',
    rank: '88',
  },
  {
    imageUrl: 'https://shohid.info/shohid/mohammad-tanvir-siddiqui.jpg',
    name: 'Mohammad Tanvir Siddiqui',
    role: 'Student',
    institution: 'Govt. Ashekane Awlia Degree College, Chittagong',
    date: '26th July, 2024',
    rank: '89',
  },
  {
    imageUrl: 'https://shohid.info/shohid/imtiaz-ahmed-zabir.jpg',
    name: 'Imtiaz Ahmed Zabir',
    role: 'Student',
    institution: 'Southeast University, Dhaka',
    date: '26th July, 2024',
    rank: '90',
  },
  {
    imageUrl: 'https://shohid.info/shohid/hridoy-ahmed-shihab.jpg',
    name: 'Shekh Hridoy Ahmed Shihab',
    role: 'Employee',
    institution: 'Employee in a furniture shop, in Badda, Dhaka',
    date: '19th July, 2024',
    rank: '91',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Shahjahan Miah',
    role: '',
    institution: '',
    date: '23th July, 2024',
    rank: '92',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Jubayer Ahmed',
    role: 'Businessman',
    institution: 'Kawla, Hajj Camp',
    date: '18th July, 2024',
    rank: '93',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Sajedur Rahman',
    role: 'Student',
    institution: '',
    date: '24th July, 2024',
    rank: '94',
  },
  {
    imageUrl: 'https://shohid.info/shohid/mohammad-tuhin.jpg',
    name: 'Mohammad Tuhin',
    role: 'Construction Worker',
    institution: 'Dhaka',
    date: '20th July, 2024',
    rank: '95',
  },
  {
    imageUrl: 'https://shohid.info/shohid/abdullah-al-tahir.jpg',
    name: 'Abdullah Al Tahir',
    role: 'Graphics Designer',
    institution: 'Srijan Graphics Printers, Siraj Market Road, Uttara, Dhaka',
    date: '18th July, 2024',
    rank: '96',
  },
  {
    imageUrl: 'https://shohid.info/shohid/emam-hasan-taim.jpg',
    name: 'Emam Hasan Taim',
    role: 'Student',
    institution: 'A. K. School and College, Dania, Dhaka',
    date: '19th July, 2024',
    rank: '97',
  },
  {
    imageUrl: 'https://shohid.info/shohid/ahasan-habib-tamim.jpg',
    name: 'Ahasan Habib Tamim',
    role: 'Student',
    institution: 'Jagannath University. ',
    date: '19th July, 2024',
    rank: '98',
  },
  {
    imageUrl: 'https://shohid.info/shohid/abdullah-al-abir.jpg',
    name: 'Abdullah Al Abir',
    role: 'Employee',
    institution: 'North South University',
    date: '20th July, 2024',
    rank: '99',
  },
  {
    imageUrl: 'https://shohid.info/shohid/roman-bepari.jpg',
    name: 'Roman Bepari',
    role: '',
    institution: '',
    date: '19th July, 2024',
    rank: '100',
  },
  {
    imageUrl: 'https://shohid.info/shohid/md-nasir-islam.jpg',
    name: 'Md. Nasir Islam',
    role: 'Student',
    institution: "Ta'mirul Millat Kamil Madrasa",
    date: '20th July, 2024',
    rank: '101',
  },
  {
    imageUrl: 'https://shohid.info/shohid/md-titu-hawladar.jpg',
    name: 'MD. Titu Hawladar',
    role: 'Driver',
    institution: 'Dhaka',
    date: '20th July, 2024',
    rank: '102',
  },
  {
    imageUrl: 'https://shohid.info/shohid/dulal-mahmud.jpg',
    name: 'Dulal Mahmud',
    role: 'Employee',
    institution: 'Standard Chartered Bank',
    date: '19th July, 2024',
    rank: '103',
  },
  {
    imageUrl: 'https://shohid.info/shohid/naima-sultana.jpg',
    name: 'Naima Sultana',
    role: 'Student',
    institution: 'Milestone School',
    date: '19th July, 2024',
    rank: '104',
  },
  {
    imageUrl: 'https://shohid.info/shohid/saiful-islam.jpg',
    name: 'Saiful Islam',
    role: 'Farmer',
    institution: 'Fulpur, Mymensingh',
    date: '20th July, 2024',
    rank: '105',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Nurul Amin',
    role: '',
    institution: '',
    date: '20th July, 2024',
    rank: '106',
  },
  {
    imageUrl: 'https://shohid.info/shohid/jobayer-ahmed.jpg',
    name: 'Jobayer Ahmed',
    role: 'Student',
    institution: 'Mojaffar Ali College',
    date: '20th July, 2024',
    rank: '107',
  },
  {
    imageUrl: 'https://shohid.info/shohid/ifat-hasan.jpg',
    name: 'Ifat hasan',
    role: 'Student',
    institution: 'A. K. School and College, Dania, Dhaka',
    date: '20th July, 2024',
    rank: '108',
  },
  {
    imageUrl: 'https://shohid.info/shohid/sahid-rohan.jpg',
    name: 'Sahid Rohan',
    role: 'Student',
    institution: 'Dania College, Shanir Akhra',
    date: '19th July, 2024',
    rank: '109',
  },
  {
    imageUrl: 'https://shohid.info/shohid/hosen-miah.jpg',
    name: 'Hosen Miah',
    role: 'Hawker',
    institution: 'Sell popcorn, ice cream and chocolate on the streets',
    date: '20th July, 2024',
    rank: '110',
  },
  {
    imageUrl: 'https://shohid.info/shohid/md-raju-ahmed.jpg',
    name: 'MD. Raju Ahmed',
    role: 'Student',
    institution: 'Adarsha College, Magura',
    date: '19th July, 2024',
    rank: '111',
  },
  {
    imageUrl: 'https://shohid.info/shohid/jarir-ahmed-didat.jpg',
    name: 'Jarir Ahmed Didat',
    role: 'Employee',
    institution: '3C Studio',
    date: '23th July, 2024',
    rank: '112',
  },
  {
    imageUrl: 'https://shohid.info/shohid/biplob-seikh.jpg',
    name: 'Biplob Seikh',
    role: 'Employee',
    institution: 'A factory in Mirpur 12 Rupnagar residential area',
    date: '19th July, 2024',
    rank: '113',
  },
  {
    imageUrl: 'https://shohid.info/shohid/al-amin-comilla.jpg',
    name: 'Al Amin',
    role: 'Student',
    institution: '',
    date: '20th July, 2024',
    rank: '114',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Wadud',
    role: 'Student',
    institution: 'Northern University',
    date: '19th July, 2024',
    rank: '115',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Huzaif Noor Habib',
    role: 'Student',
    institution: 'Blue Bird School and College',
    date: '19th July, 2024',
    rank: '116',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Golam Rabbani',
    role: 'Worker',
    institution: 'Dhaka',
    date: '20th July, 2024',
    rank: '117',
  },
  {
    imageUrl: 'https://shohid.info/shohid/ahmed-sunny.jpg',
    name: 'Ahmed Sunny',
    role: 'Student',
    institution: 'Jameul Uloom Madrasa, Mirpur',
    date: 'DIED_DATE.19/07/2014',
    rank: '118',
  },
  {
    imageUrl: 'https://shohid.info/shohid/fuad-mahamud-fahim.jpg',
    name: 'Fuad Mahamud Fahim',
    role: 'Student',
    institution: 'Northern University',
    date: '22th July, 2024',
    rank: '119',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Nabin Talukdar',
    role: 'Social Worker',
    institution: '',
    date: '19th July, 2024',
    rank: '120',
  },
  {
    imageUrl: 'https://shohid.info/shohid/syed-raju.jpg',
    name: 'Syed Raju',
    role: 'Businessman',
    institution: 'Siddhirganj, Narayanganj',
    date: '22th July, 2024',
    rank: '121',
  },
  {
    imageUrl: 'https://shohid.info/shohid/alamgir-sheikh.jpg',
    name: 'Alamgir Sheikh ',
    role: 'Driver',
    institution: 'Healthcare Pharmaceuticals Limited',
    date: '19th July, 2024',
    rank: '122',
  },
  {
    imageUrl: 'https://shohid.info/shohid/sarwar-hosen-khan-shaun.jpg',
    name: 'Sarwar Hosen Khan Shaun',
    role: 'Employee',
    institution: 'Haider Ali Prince Restaurant, Rampura',
    date: '19th July, 2024',
    rank: '123',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Md. Sumon',
    role: 'Driver',
    institution: 'Palmal Group of Industries Ltd.',
    date: '19th July, 2024',
    rank: '124',
  },
  {
    imageUrl: 'https://shohid.info/shohid/jubayer-ahmed-2.jpg',
    name: 'Jubayer Ahmed',
    role: 'Student',
    institution: 'Dhaka College',
    date: '19th July, 2024',
    rank: '125',
  },
  {
    imageUrl: 'https://shohid.info/shohid/rajon-shikdar.jpg',
    name: 'Rajon Shikdar',
    role: 'Student',
    institution: 'Dhaka Model (Degree) College, Mirpur',
    date: '19th July, 2024',
    rank: '126',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Jashim Uddin',
    role: 'Employee',
    institution:
      'He was working as a manager of an automobile shop in Uttara, Dhaka.',
    date: '18th July, 2024',
    rank: '127',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Md. Faruk',
    role: 'Employee',
    institution: 'Employee of a Chair Shop in Sholoshohor, Chattogram',
    date: '16th July, 2024',
    rank: '128',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Naim',
    role: 'Employee',
    institution: 'A private institution in Dhaka',
    date: '19th July, 2024',
    rank: '129',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Md Hasib',
    role: 'Student',
    institution: 'Northern University Bangladesh ',
    date: '20th July, 2024',
    rank: '130',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Md Akash',
    role: 'Student',
    institution: '',
    date: '21th July, 2024',
    rank: '131',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Mohammad Nuru Hussain',
    role: 'Worker',
    institution: 'Dhaka',
    date: '19th July, 2024',
    rank: '132',
  },
  {
    imageUrl: 'https://shohid.info/shohid/sabbir-mallik.jpg',
    name: 'Sabbir Mallik',
    role: 'Student',
    institution: 'Sherbangla College',
    date: '19th July, 2024',
    rank: '133',
  },
  {
    imageUrl: 'https://shohid.info/shohid/saimon-hossain.jpg',
    name: 'Saimon Hossain',
    role: 'Shop Worker',
    institution: 'Saimon worked in a grocery store in Bahaddarhat',
    date: '18th July, 2024',
    rank: '134',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Yamin Chowdhury',
    role: 'Garment Worker',
    institution: 'FNF Garments, Badda',
    date: '27th July, 2024',
    rank: '135',
  },
  {
    imageUrl: 'https://shohid.info/shohid/abdul-ahad.jpg',
    name: 'Abdul Ahad',
    role: 'Child',
    institution: '',
    date: '19th July, 2024',
    rank: '136',
  },
  {
    imageUrl: 'https://shohid.info/shohid/md-rasel.jpg',
    name: 'Md. Rasel',
    role: 'Garment Worker',
    institution: 'A garment factory in Narayanganj',
    date: '19th July, 2024',
    rank: '137',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Md. Mainuddin',
    role: 'Teacher',
    institution: 'Mainuddin used to teach part-time in a local madrasa.',
    date: '26th July, 2024',
    rank: '138',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Ehsan Habib',
    role: 'Employee',
    institution: 'BRB Cable Industries Ltd.',
    date: '18th July, 2024',
    rank: '139',
  },
  {
    imageUrl: 'https://shohid.info/shohid/alem-al-faydee.jpg',
    name: 'Alem Al Faydee',
    role: 'Intern',
    institution: 'Auto Museum Ltd.',
    date: '19th July, 2024',
    rank: '140',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Yasin',
    role: 'Worker',
    institution: 'Yasin worked in a local gas cylinder shop',
    date: '26th July, 2024',
    rank: '141',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Md. Hosen',
    role: 'Driver',
    institution: '',
    date: '18th July, 2024',
    rank: '142',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Sohag',
    role: 'Hawker',
    institution: '',
    date: '19th July, 2024',
    rank: '143',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Nur Alam',
    role: 'Construction Worker',
    institution: 'Gazipur, Contract worker(Construction)',
    date: '20th July, 2024',
    rank: '144',
  },
  {
    imageUrl: 'https://shohid.info/shohid/roni-pramanik.jpg',
    name: 'Roni Pramanik',
    role: 'Rickshaw Puller',
    institution: '',
    date: '20th July, 2024',
    rank: '145',
  },
  {
    imageUrl: 'https://shohid.info/shohid/biplob-hasan.jpg',
    name: 'Biplob Hasan',
    role: 'Student',
    institution: 'Mojaffor Ali Faquir High School',
    date: '20th July, 2024',
    rank: '146',
  },
  {
    imageUrl: 'https://shohid.info/shohid/nure-alam-siddiqui-rakib.jpg',
    name: 'Nure Alam Siddiqui Rakib',
    role: 'Student',
    institution: "Ta'limul Quran Mohila Madrasah",
    date: '20th July, 2024',
    rank: '147',
  },
  {
    imageUrl: 'https://shohid.info/shohid/md-foyez.jpg',
    name: 'Md. Foyez',
    role: 'PROFESSIONS.PLUMBER',
    institution: 'Jatrabari, Dhaka',
    date: '21th July, 2024',
    rank: '148',
  },
  {
    imageUrl: 'https://shohid.info/shohid/shawn-shikder.jpg',
    name: 'Shawn Shikder',
    role: 'PROFESSIONS.TILES_REPAIRER',
    institution: 'Tiles repairer, Dhaka',
    date: '19th July, 2024',
    rank: '149',
  },
  {
    imageUrl: 'https://shohid.info/shohid/mamun-hosen.jpg',
    name: 'Mamun Hosen',
    role: 'Driver',
    institution: 'Driver, Dhaka',
    date: '20th July, 2024',
    rank: '150',
  },
  {
    imageUrl: 'https://shohid.info/shohid/zakir-hosen.jpg',
    name: 'Zakir Hosen',
    role: 'Garment Worker',
    institution: 'Kazi VIP Garments, Vim Bazar, Gazipur',
    date: '21th July, 2024',
    rank: '151',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Sohel Rana',
    role: '',
    institution: '',
    date: '25th July, 2024',
    rank: '152',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Zakir Hosen',
    role: 'Tailor',
    institution: '',
    date: '25th July, 2024',
    rank: '153',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Mohammad Imran',
    role: 'Chef',
    institution: '',
    date: '18th July, 2024',
    rank: '154',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Md. Sajib',
    role: 'Employee',
    institution: 'Paint Shop',
    date: '21th July, 2024',
    rank: '155',
  },
  {
    imageUrl: 'https://shohid.info/shohid/amjad-hosen.jpg',
    name: 'Amjad Hosen',
    role: 'Student',
    institution: 'Govt. Shahid Asad College, Shibpur, Narsingdi.',
    date: '18th July, 2024',
    rank: '156',
  },
  {
    imageUrl: 'https://shohid.info/shohid/md-moinul-islam.jpg',
    name: 'Md, Moinul Islam',
    role: 'Teacher',
    institution: 'Ahsanul Hikmah Madrasah, Demra, Dhaka',
    date: '21th July, 2024',
    rank: '157',
  },
  {
    imageUrl: 'https://shohid.info/shohid/md-abdul-kaium-ahad.jpg',
    name: 'Md. Abdul Kaium Ahad',
    role: 'PROFESSIONS.AC_MECHANIC',
    institution: 'Jatrabari, Dhaka',
    date: '18th July, 2024',
    rank: '158',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Maya Islam',
    role: 'Housewife',
    institution: 'Banasree,Dhaka',
    date: '19th July, 2024',
    rank: '159',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Abu Sayed',
    role: 'Rickshaw Puller',
    institution: 'Bosila, Mohammadpur, Dhaka',
    date: '19th July, 2024',
    rank: '160',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Md. Abdul Wadud',
    role: 'Businessman',
    institution: 'Priangon Shopping Center, Dhaka',
    date: '19th July, 2024',
    rank: '161',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Mukhlesur Rahman',
    role: 'Employee',
    institution: '',
    date: '19th July, 2024',
    rank: '162',
  },
  {
    imageUrl: 'https://shohid.info/shohid/md-shovon.jpg',
    name: 'Md. Shovon',
    role: 'Student',
    institution: 'Shaikh Burhanuddin Post Graduate College',
    date: '19th July, 2024',
    rank: '163',
  },
  {
    imageUrl: 'https://shohid.info/shohid/abu-bakkar-shiblu.jpg',
    name: 'Abu Bakkar Shiblu',
    role: 'Businessman',
    institution: 'Uttara, Dhaka',
    date: '25th July, 2024',
    rank: '164',
  },
  {
    imageUrl: 'https://shohid.info/shohid/minhajul-islam.jpg',
    name: 'Minhajul Islam',
    role: 'Garment Worker',
    institution: 'New Commence Fashion Ltd.',
    date: '20th July, 2024',
    rank: '165',
  },
  {
    imageUrl: 'https://shohid.info/shohid/tajul-islam.jpg',
    name: 'Tajul Islam',
    role: 'Rent-a-Car Owner',
    institution: 'Azampur, Uttara, Dhaka',
    date: '18th July, 2024',
    rank: '166',
  },
  {
    imageUrl: 'https://shohid.info/shohid/mizanur-rahman.jpg',
    name: 'Mizanur Rahman',
    role: 'Employee',
    institution: 'A beauty parlour in Norda Area',
    date: '21th July, 2024',
    rank: '167',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Zaman Miah',
    role: 'Garment Worker',
    institution: 'Mymensingh',
    date: '25th July, 2024',
    rank: '168',
  },
  {
    imageUrl: 'https://shohid.info/shohid/abu-jafor.jpg',
    name: 'Abu Jafor',
    role: 'PROFESSIONS.BUS_DRIVER',
    institution: 'Shyamoli Paribahan',
    date: '18th July, 2024',
    rank: '169',
  },
  {
    imageUrl: 'https://shohid.info/shohid/nazmul-hasan.jpg',
    name: 'Nazmul Hasan',
    role: 'Student',
    institution: 'Dhaka Imperial college',
    date: '19th July, 2024',
    rank: '170',
  },
  {
    imageUrl: 'https://shohid.info/shohid/ashikul-islam.jpg',
    name: 'Ashikul Islam',
    role: 'Student',
    institution: 'Jahanjhar Di-mukhi Dakhil Madrasa',
    date: '19th July, 2024',
    rank: '171',
  },
  {
    imageUrl: 'https://shohid.info/shohid/mizan-howladar.jpg',
    name: 'Mizan Howladar',
    role: 'Day Laborer',
    institution: 'Maniknagar,Mugda, Dhaka',
    date: '20th July, 2024',
    rank: '172',
  },
  {
    imageUrl: 'https://shohid.info/shohid/sumaiya-akter.jpg',
    name: 'Sumaiya Akter',
    role: 'Housewife',
    institution: '',
    date: '20th July, 2024',
    rank: '173',
  },
  {
    imageUrl: 'https://shohid.info/shohid/mohammad-ali.jpg',
    name: 'Mohammad Ali',
    role: 'Businessman',
    institution: '',
    date: '21th July, 2024',
    rank: '174',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Sakib Hasan',
    role: 'Student',
    institution: '',
    date: '17th July, 2024',
    rank: '175',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Saad Mahmud',
    role: 'Student',
    institution: 'Jabale Nur Dakhil Madrasa',
    date: '20th July, 2024',
    rank: '176',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Md Atique',
    role: 'Employee',
    institution: 'At a Buying House at Uttara',
    date: '18th July, 2024',
    rank: '177',
  },
  {
    imageUrl: 'https://shohid.info/shohid/monayel-ahmed-imran-asad.jpg',
    name: 'Monayel Ahmed Imran Asad',
    role: 'Student',
    institution: '',
    date: '21th July, 2024',
    rank: '178',
  },
  {
    imageUrl: 'https://shohid.info/shohid/unknown-dead-body.jpg',
    name: 'Jamal Shikder',
    role: '',
    institution: '',
    date: '20th July, 2024',
    rank: '179',
  },
  {
    imageUrl: 'https://shohid.info/shohid/md-sakib-rayhan.jpg',
    name: 'Md. Sakib Rayhan',
    role: 'Employee',
    institution: '',
    date: '19th July, 2024',
    rank: '180',
  },
];
